[package]
name = "raven-varvara"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono.workspace = true
log.workspace = true
static_assertions.workspace = true
zerocopy.workspace = true

uxn = { path = "../raven-uxn", package = "raven-uxn", default-features = false }
