[package]
name = "raven-gui"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
eframe.workspace = true
env_logger.workspace = true
log.workspace = true

varvara = { path = "../raven-varvara", package = "raven-varvara" }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
clap.workspace = true
cpal.workspace = true
uxn = { path = "../raven-uxn", package = "raven-uxn" }

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen-futures.workspace = true
web-sys.workspace = true
cpal = { workspace = true, features = ["wasm-bindgen"] }
uxn = { path = "../raven-uxn", package = "raven-uxn", default-features = false, features = ["alloc"] }
